services:
  api-financeiro:
    container_name: api-financeiro
    build:
      context: .docker/node/
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    entrypoint: sh .docker/node/entrypoint.sh
    ports:
      - '3005:3005'
      - '7005:7005'
    volumes:
      - .:/home/node/app
    networks:
      - codelab-net

  db-financeiro:
    container_name: db-financeiro
    build:
      context: ./.docker/postgres
      dockerfile: Dockerfile
    command: postgres -c log_statement=all -p 5005
    volumes:
      - '.docker/postgres/data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=api-financeiro
    ports:
      - '5005:5005'
    networks:
      - codelab-net

networks:
  codelab-net:
    name: codelab-net
    external: true
